TOTAL_PAGES = '//span[@class="result"]/em/text()'
HOUSE_LINKS = '//a[@class="favor-pos"]/@href'
TELEPHONE = '//i[@class="lp-rig-tel"]/span/text()'
SALE_STATUS = '//i[contains(@class, "can-tag-status")]/text()'
ITEMS = '//div[@class="can-left"]//li'
NAME = './div[@class="name"]/text()'
ROOM_COUNT = '//span[@class="hx-results"]/em/text()'
ROOM_URLS = '//ul[@class="hx-list g-clear"]/li/a/@href'
ROOM_TYPE_PICS = '//div[@id="j-switch-hx-m"]//li'
ROOM_TITLES = '//div[@class="hx-de-right"]/h3/span/text()'
ROOM_LABELS = '//div[@class="hx-de-right"]/p[@class="tag-wrap"]/span/text()'
ROOM_PRICE = '//div[@class="hx-de-right"]/p[position()>1]'
