TOTAL_PAGES = '//span[@class="result"]/em/text()'
HOUSE_LINKS = '//a[@class="favor-pos"]/@href'
TELEPHONE = '//div[@class="lp-rig-tel"]/span/text()'
SALE_STATUS = '//i[contains(@class, "can-tag-status")]/text()'
ITEMS = '//div[@class="can-left"]//li'
NAME = './div[@class="name"]/text()'
ROOM_COUNT = '//span[@class="hx-results"]/em/text()'
ROOM_URLS = '//ul[@class="hx-list g-clear"]/li/a/@href'
ROOM_TYPE_PICS = '//div[@id="j-switch-hx-m"]//li'
ROOM_TITLES = '//div[@class="hx-de-right"]/h3/span/text()'
ROOM_LABELS = '//div[@class="hx-de-right"]/p[@class="tag-wrap"]/span/text()'
ROOM_PRICE = '//div[@class="hx-de-right"]/p[position()>1]'
ROOM_DETAILS = '//div[@class="hx-de-right"]/div[@class="hx-detail-wrap"]/p'
ROOM_DESCRIPTION = '//div[@class="hx-de-right"]/div[@class="hx-des-wrap"]/p/span/text()'
PIC_HEADER = '//div[@class="album-head"]/a[position()>1]/text()'
PIC = '//div[@class="others-pic"]//li'
PICTORIAL = '//div[@class="pictorial"]//a[@class="p-item"]/@href'
PIC_ITEMS = '//div[@id="j-switch-picts"]//div[@class="item"]'