TOTAL_COUNT = '//span[@class="s-m-fr"]/strong/text()'
HOUSE_IDS = '//div[@id="bd-left"]//div[contains(@class, "s-lp-all")]/@event-tracking-param-project'
OTHER_NAME = '//span[@class="loupan-other-name"]/text()'
LABELS = '//ul[contains(@class, "tag-list")]/li[position()>1]/text()'
INFO = '//div[@id="bd-left"]//tr'
LICENSE = '//div[contains(@class, "saleLicense")]//tr'
PRICE = '//div[@id="prizeinfo"]//tr'
DESCRIPTION = '//div[@id="lpdes"]/p[@class="panel-para"]/text()'
PICTURE_URLS = '//div[@class="sub-menu-wrap"]//a'
PICTURES = '//div[@class="lv-sm-list"]//img'
ROOM = '//div[@class="module-lphuxing"]/dl/dd/@data-link'
ROOM_PICS = '//div[@class="slide-div"]//img/@src'
ROOM_TYPE = '//div[@class="right-wrap"]/div[1]/h1/text()'
SALE_STATUS ='//div[@class="right-wrap"]/div[1]/p/strong/text()'
ROOM_PRICE = '//div[@class="ck-div"]//text()'
ROOM_INFO = '//div[@class="info-bom pt15"]/div[@class="info-p"]/div'
ROOM_DESCRIPTION = '//div[@class="right-wrap"]/div/div/label[text()="户型解析："]'

